### ISSUE TITLE
Preserve and cite the notebook

### ISSUE THREAD

**Issue by glouppe** [glouppe/talk-aleph-workshop2015#1]
Would you have ideas on how we could in practice make the notebook citable? I am not convinced we have enough materials to make this into a paper, but a least it would be nice if we could preserve and cite the notebook in some way or another. 

CC @betatim (or maybe @cranmer knows how to do that?)

**Comment by betatim** [comment]
The first two that come to mind are:
- https://zenodo.org/ 
- http://figshare.com/

not sure I know enough about them to know how to distinguish them beyond taste. There is also https://mozillascience.github.io/code-research-object/ which connects github with figshare(??).

At MozFest there were a few people grumbling about figshare not being open, which I think is related to them being a for profit company(??), so maybe zenodo?

**Comment by cranmer** [comment]
Yes, I would do github repo -> zenodo option.
I'm actually doing that now for a different reason.

Kyle

**Comment by glouppe** [comment]
Thanks for the suggestion! We now have http://dx.doi.org/10.5281/zenodo.34631 for the repo (in which I added the notebook file)

**Comment by cranmer** [comment]
Nice!
Too bad zenodo doesn’t render the notebook as well. Maybe that is in the future.

Kyle

**Comment by glouppe** [comment]
I guess this is due to how Zenodo integrates with GitHub? (i.e., zipping everything and then attaching the archive to the Zenodo record, instead of attaching all individual files) I wonder how different would be the Zenodo record if I uploaded the files by hand instead (for which in-browser previsualization might then kick in). CC: @lnielsen for some user support :)

**Comment by cranmer** [comment]
Yeah for sure.
I was searching for a zenodo entry with an ipynb to see if zenodo will render, but I couldn’t find one.
This might be planned for the future, I know Zenodo and ivenio are undergoing some major developments.

Kyle

**Comment by lnielsen** [comment]
@glouppe We unfortunately don't have notebook previewer yet :(

**Comment by betatim** [comment]
Can you modify the short description on the page of the record an include a direct link to the notebook rendered with nbviewer?

Zenodo questions:
- Should there be a button to edit things for me as a co-author or is it all up to the first author?
- When I click my [name](https://zenodo.org/search?f=author&p=Tim%20Head&ln=en) I see two publications in the journal of brief ideas but not this one. Is that just a question of waiting for the index to update?
- How does it work out my affiliation? I used to be CERN but now EPFL :-/
